apiVersion: apps/v1
kind: Deployment 
metadata:
  name: geogit-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:  
    metadata:
      name: frontend-pod
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: devaksdemo.azurecr.io/sysapp:#{Build.BuildId}#
          ports: 
            - containerPort: 80