apiVersion: v1
kind: Service 
metadata:
  name: front-end-loadbalancer-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: frontend
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port